import 'bootstrap/dist/css/bootstrap.min.css';     // 설치한 패키지에서 CSS 읽어옴
import 'bootstrap-icons/font/bootstrap-icons.css'; // 아이콘 (선택)
import Script from 'next/script';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
    </html>
  )
}
